name = "JuliaLowering"
uuid = "f3c80556-a63f-4383-b822-37d64f81a311"
authors = ["Claire Foster <aka.c42f@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
